name: 'Nala'

inputs:
  test-type:
    description: 'Type of test to run'
    required: true
    default: 'nala'

runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: Run tests
      shell: bash
      run: |
        if [ "${{ inputs.test-type }}" == "caas" ]; then
          $GITHUB_ACTION_PATH/run.sh -type @caas
        else
          $GITHUB_ACTION_PATH/run.sh
        fi
