version: 2.1

parameters:
  env:
    type: string
    default: prod
  branch:
    type: string
    default: none

orbs:
  node: circleci/node-example@1

jobs:
  test:
    docker:
      - image: <some_image>
    environment:
      ENV: << pipeline.parameters.env >>
      BRANCH: << pipeline.parameters.branch >>
    steps:
      - node/install:
          node-version: '16.16.0'
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
      - run: |
          npm install
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: |
          npx playwright install-deps
          npx playwright install
      - run:
          name: Set env variables
          command: |
            <set up environment variables command>
      - run:
          name: Run specific group of tests 1
          no_output_timeout: 30m
          command: |
            <Test(s) category 1 execution>
      - run:
          name: Run specific group of tests 2
          no_output_timeout: 30m
          command: |
            <Test(s) category 2 execution>
      - store_artifacts:
          path: reports
      - run:
          when: on_fail
          command: |
            <Command to run when tests fail>
      - run:
          when: on_success
          command: |
            <Command to run when tests succeed>


workflows:
  run:
    jobs:
      - test
