name: Pre-release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yml
  pre-release:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Pre-release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: 'Janus Latest Build'
